### PR TITLE
Update admin-page.php

### PR DESCRIPTION
**Pull request by KTS915**
Just a suggestion to change from jQuery to plain JavaScript.

### CODE REVIEW

**Comment by KTS915** [comment]
Doesn't that make the plain JavaScript version better? The selector should _always_ be available, so it _should_ throw an error if it isn't.

**Comment by joyously** [comment]
I guess there are two interpretations of "better".
I would label no errors better than possible errors.
I have written code just like yours, thinking the element should always be there, and then something unrelated changes or a scenario I never thought of happens, and my code breaks (gives an error).

I wonder if the original is even accessible.  Why is this code in the page, anyway?

**Comment by KTS915** [comment]
> I wonder if the original is even accessible.
It isn't accessible. But that's a matter for a different PR.

>I would label no errors better than possible errors.
Of course. But that's not the comparison being made here. What we're talking about here is _if there is an error_, should it be reported. To which the answer surely is an emphatic yes. So the vanilla version is superior.

The selector should always be present because it's created by this very plugin. If it doesn't exist, then that is very definitely an error that needs to be reported, not suppressed or overlooked.

**Comment by KTS915** [comment]
No, it just ensures that the code can't run when the selector doesn't exist. But there is an unreported error there, because the code _should_ exist. Of course the user needs to see it because they need to be able to report the error message to a developer. We all know that "doesn't work" is a pretty useless report.

**Review by mattyrob — APPROVED** [review]

**Pull request merged**
