### PR TITLE
add text to the switching screen

### PR DESCRIPTION
**Pull request by senlin**
Add text to the switching screen to inform the user of what is going to happen and that it can take a while.

Also add the ClassicPress slogan

### CODE REVIEW

**Comment by nylen** [comment]
We need to make all of these strings available for translation, otherwise this is a good starting point.  Can you update the PR with the appropriate calls please?  Something like this:

```php
<p>
    <?php _e( 'text string here', 'switch-to-classicpress' ); ?>
</p>
```

**Comment by senlin** [comment]
Of course, sorry for that, wasn't thinking about that.

**Comment by senlin** [comment]
By the way, there might be an issue with the textdomain/slug. According to the WP Plugin Guidelines the textdomain and the slug need to be the same. In this case, the textdomain is `switch-to-classicpress`, but earlier today I asked @scottybo what the slug is and that is much longer: `switch-to-classicpress-from-wordpress`

**Comment by nylen** [comment]
As discussed on Slack, we're going to see if we can change the plugin slug.

PR looks good, thanks for the improvements.

**Pull request merged**
