### PR TITLE
Changed all wording to "upgrade" versus "switch" and "migrate"

### PR DESCRIPTION
**Pull request by striebwj**
Closes #36

### CODE REVIEW

**Comment by striebwj** [comment]
@nylen clearly I am overtired as I was certain I got all of them. Time for bed! 

I have done the change to the forum as well, but I will hold onto that until tomorrow so I can properly double check it this time 🙂

**Comment by nylen** [comment]
@striebwj I thought about it some more and decided to go ahead and change all wording in the code, including the plugin slug and zip filename for when we build a new version.

I left alone references to the Slack channel, this repo name, and `?migrate=classicpress` (this will eventually be used for `?migrate=wordpress` when we implement this).

I tested locally but another pair of eyes would be good in case I missed something too.

**Comment by striebwj** [comment]
@nylen I will double check everything in the morning 🙂

**Comment by striebwj** [comment]
@nylen everything looks good, I just ran through it again.

**Pull request merged**
