### PR TITLE
add link to Switch page on main plugins page

### PR DESCRIPTION
**Pull request by senlin**
For some reason this only takes on the root plugin file

addresses #13

### CODE REVIEW

**Comment by nylen** [comment]
@senlin did you test with the latest version of the plugin?

This is already implemented, and it's working for me:

https://github.com/ClassicPress/ClassicPress-Migration-Plugin/blob/master/lib/admin-page.php#L24-L46

Here's the result:

switch-to-classicpress

I don't mind if we pick your way, especially if it works for you but the existing code doesn't.  In that case let's remove the existing code I linked above.

**Comment by senlin** [comment]
Yes, that piece of code is in the files that I have too, and it indeed doesn't work for me.

**Comment by senlin** [comment]
added it, but because I work from a patch it has become a separate PR, sorry.

**Comment by nylen** [comment]
Ok, no problem. I'll sort through them "soon" :)

**Pull request merged**
